FROM node:20-alpine AS base
WORKDIR /app
COPY apps/web/package.json ./apps/web/package.json
COPY package.json pnpm-workspace.yaml turbo.json ./
COPY packages/shared ./packages/shared
RUN npm install -g pnpm && pnpm install --filter @caoms/web --frozen-lockfile || pnpm install --filter @caoms/web
COPY apps/web ./apps/web
WORKDIR /app/apps/web
EXPOSE 3000
CMD ["npm","run","dev","--","--port","3000","--hostname","0.0.0.0"]
